name: Custom Rom Builder Samsung Galaxy A11/M11

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image '
        required: true
        default: 'https://github.com/Doze-off/crdroid_gsi_treble/releases/download/2025-08-02/crDroid-12.0_GSI_treble_arm64-ab_MICROG-20250802.img.xz'        
      ARCH:
        description: 'ARM64 or ARM32?'
        required: true
        default: '64'                
      NAME:
        description: 'Crdroid 12 for Samsung Galaxy M11'
        required: true
        default: 'crDroid.12_0_A11_M11_ARM64_VANILLA'                

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        wget https://sourceforge.net/projects/samsung-galaxy-a01-m01/files/a11q.zip
        git clone https://github.com/SamsungSDM439/Custom-Rom-Builder-For-Samsung-Galaxy-A01-M01
        unzip a11q.zip
        rm -r a11q.zip

    - name: Downloading your GSI
      run: |
        wget -P "./temp" ${{ github.event.inputs.GSI }} 
        chmod 755 *
        chmod 755 ./bin/*

    - name: Building
      run: |
        ./arm${{ github.event.inputs.ARCH }}_git
        
    - name: Uploading The Zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.NAME }}   # Replace with a suitable name
        path: ./zip/Custom_Rom_SDM450.zip
